export const committeeLevels = [
  {
    key: "CA",
    label: "CA",
    title: "Maintenu",
    description: "Niveau attendu a consolider avec un suivi clair.",
    tone: "bg-[#E7EDF3] text-[#0F4A72] border-[#C9D8E6]",
  },
  {
    key: "CB",
    label: "CB",
    title: "Passable",
    description: "Bases presentes, progression encore necessaire.",
    tone: "bg-[#E8F0FA] text-[#1F5F8B] border-[#B8D3EA]",
  },
  {
    key: "CC",
    label: "CC",
    title: "Bien",
    description: "Performance solide et contribution fiable.",
    tone: "bg-[#DDECCF] text-[#4E8B1B] border-[#A8D28A]",
  },
  {
    key: "CD",
    label: "CD",
    title: "Excellent",
    description: "Performance remarquable, forte autonomie.",
    tone: "bg-[#DDE9FF] text-[#244E9A] border-[#9DB7F0]",
  },
];

export const committeeMembers = [
  "Isabella Sinclair BEDA",
  "Revita Oule",
  "Augustin KPANTCHE",
  "Stephane GNAHOUA",
  "Axelle AMANI",
  "Stephanie TAKI",
  "Yves DODO",
];

export const committeeAssistants = [
  {
    id: "habib-bah",
    name: "Habib Bah",
    role: "Assistant expertise comptable",
    department: "Expertise comptable",
    manager: "Stephane GNAHOUA",
    score: "3.2",
    level: "CB",
  },
  {
    id: "orlane-kone",
    name: "Orlane Kone",
    role: "Assistante expertise comptable",
    department: "Expertise comptable",
    manager: "Stephane GNAHOUA",
    score: "3.6",
    level: "CC",
  },
  {
    id: "kader-kone",
    name: "Kader Kone",
    role: "Assistant expertise comptable",
    department: "Expertise comptable",
    manager: "Stephane GNAHOUA",
    score: "2.9",
    level: "CA",
  },
  {
    id: "yves-audit",
    name: "Yves ",
    role: "Assistant audit",
    department: "Audit",
    manager: "Axelle AMANI",
    score: "3.9",
    level: "CC",
  },
  {
    id: "moussa-traore",
    name: "Moussa Traore",
    role: "Assistant audit",
    department: "Audit",
    manager: "Stephanie TAKI",
    score: "4.3",
    level: "CD",
  },
];

export const committeeLeaders = [
  {
    id: "isabella-beda",
    name: "Isabella Sinclair BEDA",
    role: "RH",
    department: "RH",
    manager: "Associés",
    score: "-",
    level: "CC",
  },
  {
    id: "revita-oule",
    name: "Revita Oule",
    role: "Manager",
    department: "Conseil operationnel",
    manager: "Associés",
    score: "-",
    level: "CC",
  },
  {
    id: "augustin-kpantche",
    name: "Augustin KPANTCHE",
    role: "Manager",
    department: "Conseil financier",
    manager: "Associés",
    score: "-",
    level: "CC",
  },
  {
    id: "stephane-gnahoua",
    name: "Stephane GNAHOUA",
    role: "Manager",
    department: "Expertise comptable",
    manager: "Associés",
    score: "-",
    level: "CC",
  },
  {
    id: "axelle-amani",
    name: "Axelle AMANI",
    role: "Manager",
    department: "Audit",
    manager: "Associés",
    score: "-",
    level: "CD",
  },
  {
    id: "stephanie-taki",
    name: "Stephanie TAKI",
    role: "Manager",
    department: "Audit",
    manager: "Associés",
    score: "-",
    level: "CD",
  },
];

export const committeeSupport = [
  {
    id: "support-admin",
    name: "Support administratif",
    role: "Support",
    department: "Support",
    manager: "Associés",
    score: "-",
    level: "CB",
  },
  {
    id: "support-it",
    name: "Support IT",
    role: "Support",
    department: "Support",
    manager: "Associés",
    score: "-",
    level: "CB",
  },
];
